#!/usr/bin/php
<?php

/* This crontab adds/remove FPM pools for php 5.6 to 8.2
   for each user who uses a fpm configuration
*/
   
require_once("/usr/share/alternc/panel/class/config_nochk.php");

function myecho($str) {
	 static $first=true;
	 if ($first) {
	    echo date("Y-m-d H:i:s")." Log of php7-fpm\n";
	    $first=false;
	 }
	 echo $str."\n";
}

// If using prefixes, check if the prefix changed
// If the prefix changed, we must rebuild the pools
$db_user_prefix=variable_get("user_prefix");
if (!is_null($db_user_prefix)) {
    // retrieve currently used prefix
    $db->query("SELECT login FROM membres LIMIT 1;");
    $record=$db->fetch();
    $first_user = $record['login'];
    $current_prefix = exec("grep '/$first_user:' /var/lib/extrausers/passwd | cut -d ':' -f1 | sed s/$first_user//");
    // Launch a complete conf rebuild if it doesn't match
    if($db_user_prefix != $current_prefix) {
        myecho("User prefixes don't match!\nDB prefix: $db_user_prefix / current prefix: $current_prefix");
        myecho("Launching pools rebuild");
        passthru("/usr/lib/alternc/php7-fpm_rebuild_pools");
        exit;
    }
}

// first launch sync_unix since we NEED unix user to exist!
passthru("/usr/lib/alternc/install.d/alternc-nss end");

$force = (isset($argv[1]) && $argv[1]=="force");

$db->query("SELECT DISTINCT m.login,m.uid,sd.type FROM sub_domaines sd, membres m WHERE m.uid=sd.compte AND sd.type IN ('php56-fpm','php70-fpm','php71-fpm','php72-fpm','php73-fpm','php74-fpm','php80-fpm','php81-fpm','php82-fpm');");

$reload=array();
$allpools=array();
$allversions=array("5.6","7.0","7.1","7.2","7.3","7.4","8.0","8.1","8.2");

// detect installed versions
foreach($allversions as $k=>$version) {
    if (!is_dir("/etc/php/$version/fpm/pool.d")) {
        unset($allversions[$k]);
    }
}

while ($db->next_record()) {
      $version=substr($db->f("type"),3,1).".".substr($db->f("type"),4,1);
      $user=$db->f("login");
      // Add user prefix support
      $prefixed_user=$user;
      $user_prefix=variable_get("user_prefix");
      if (!is_null($user_prefix)) {
          $prefixed_user=$user_prefix.$user;
      }
      $allpools[$version][]=$user;
      if ($force || !is_file("/etc/php/".$version."/fpm/pool.d/".$user.".alternc.conf")) {
          myecho("Creating php $version fpm pool for user $user");
          $template=file_get_contents("/etc/alternc/templates/php/fpm-".$version); 
          $template=str_replace("%%PREFIXED_LOGIN%%", $prefixed_user, $template);
          $template=str_replace("%%LOGIN%%",$user, $template);
          file_put_contents("/etc/php/".$version."/fpm/pool.d/".$user.".alternc.conf", $template);
          $reload[$version]=$version;
      }
}

// now delete pools we don't need anymore
foreach($allversions as $version) {
    $d=opendir("/etc/php/$version/fpm/pool.d");
    while (($c=readdir($d))!==false) {
        if (preg_match('#([^\.]*).alternc.conf$#',$c,$mat)) {
            $user=$mat[1];
            if (!in_array($user,$allpools[$version])) {
                myecho("Deleting php $version fpm pool for user $user");
                @unlink("/etc/php/".$version."/fpm/pool.d/".$user.".alternc.conf");
                $reload[$version]=$version;
            }
        }
    }
}

// now reloads php fpm versions
foreach($reload as $service) {
    passthru("/etc/init.d/php".$service."-fpm reload || /etc/init.d/php".$service."-fpm start");  
}

